#!/usr/bin/env python3
"""Write font8x8.h (printable ASCII, 8x8, MSB = left pixel) from a PSF console font.

The default is Lat15-VGA8 from console-setup, the 8x8 VGA BIOS face, which stays legible at
the DS's 256x192 where a vector font rasterised to 8 pixels does not. Console fonts are public
domain (console-setup's copyright file).

usage: genfont.py [font.psf[.gz]] > font8x8.h
"""
import gzip, struct, sys

path = sys.argv[1] if len(sys.argv) > 1 else "/usr/share/consolefonts/Lat15-VGA8.psf.gz"
raw = (gzip.open if path.endswith(".gz") else open)(path, "rb").read()

if raw[:2] == b"\x36\x04":                      # PSF1
    mode, h = raw[2], raw[3]
    count = 512 if mode & 1 else 256
    w, glyphs_off, has_tab = 8, 4, bool(mode & 2)
    tab_off = glyphs_off + count * h
    def table():
        out, i, g = {}, tab_off, 0
        while g < count and i + 2 <= len(raw):
            u = struct.unpack_from("<H", raw, i)[0]; i += 2
            if u == 0xFFFF: g += 1
            elif u != 0xFFFE: out.setdefault(u, g)
        return out
elif raw[:4] == b"\x72\xb5\x4a\x86":            # PSF2
    _, hdr, flags, count, size, h, w = struct.unpack_from("<IIIIIII", raw, 4)
    glyphs_off, has_tab = hdr, bool(flags & 1)
    tab_off = hdr + count * size
    def table():
        out, i, g = {}, tab_off, 0
        while g < count and i < len(raw):
            if raw[i] == 0xFF: g += 1; i += 1; continue
            if raw[i] == 0xFE: i += 1; continue
            j = i
            while raw[j] not in (0xFE, 0xFF): j += 1
            for ch in raw[i:j].decode("utf-8", "ignore"): out.setdefault(ord(ch), g)
            i = j
        return out
else:
    sys.exit("not a PSF font")
if w != 8 or h != 8:
    sys.exit("need an 8x8 font, this one is %dx%d" % (w, h))
umap = table() if has_tab else {c: c for c in range(256)}

print("/* Generated by genfont.py from %s (public domain console font). */" % path.split("/")[-1])
print("static const unsigned char kFont8x8[95][8] = {")
for c in range(32, 127):
    g = umap.get(c, c)
    rows = raw[glyphs_off + g * h: glyphs_off + g * h + 8]
    ch = chr(c).replace("\\", "\\\\").replace("'", "\\'")
    print("    {%s},  /* '%s' */" % (", ".join("0x%02x" % b for b in rows), "\\\\" if c == 92 else chr(c)))
print("};")
