#!/usr/bin/env python3
# Generate font8x8.h (ASCII 32..126, 8x8 one bit per pixel, row-major, bit 7 = left)
# from DejaVu Sans Mono. Run once; the output is checked in.
from PIL import Image, ImageDraw, ImageFont
import sys
font = ImageFont.truetype("/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf", 9)
rows = []
for cp in range(32, 127):
    im = Image.new("L", (8, 8), 0)
    d = ImageDraw.Draw(im)
    d.text((0, -2), chr(cp), fill=255, font=font)
    bits = []
    for y in range(8):
        b = 0
        for x in range(8):
            if im.getpixel((x, y)) >= 110: b |= 0x80 >> x
        bits.append(b)
    rows.append(bits)
with open(sys.argv[1] if len(sys.argv) > 1 else "font8x8.h", "w") as f:
    f.write("/* Generated by genfont.py from DejaVu Sans Mono (Bitstream Vera license). */\n")
    f.write("static const unsigned char kFont8x8[95][8] = {\n")
    for cp, bits in zip(range(32, 127), rows):
        f.write("    {" + ", ".join("0x%02x" % b for b in bits) + "},  /* %r */\n" % chr(cp))
    f.write("};\n")
# preview
pv = Image.new("L", (8 * 32, 8 * 3), 0)
for i, bits in enumerate(rows):
    for y in range(8):
        for x in range(8):
            if bits[y] & (0x80 >> x): pv.putpixel((8 * (i % 32) + x, 8 * (i // 32) + y), 255)
pv.resize((pv.width * 4, pv.height * 4), Image.NEAREST).save("/tmp/claude-1000/-work-GammaOSNextDistribution-A14/ee24042b-d89e-40eb-a73c-4b414df51c0d/scratchpad/font.png")
